version: '3.8'

services:
  client:
    build:
      context: ./client
    ports:
      - "3000:80"
    env_file:
      - ./client/.env
    depends_on:
      - server

  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    environment:
      - NODE_ENV=production
