export const POSTS_FETCH = "POSTS_FETCH";
export const POSTS_FETCH_START = "POSTS_FETCH_START";
export const POSTS_FETCH_SUCCESS = "POSTS_FETCH_SUCCESS";
export const POSTS_FETCH_ERROR = "POSTS_FETCH_ERROR";


export const POST_FETCH = "POST_FETCH";
export const POST_FETCH_START = "POST_FETCH_START";
export const POST_FETCH_SUCCESS = "POST_FETCH_SUCCESS";
export const POST_FETCH_ERROR = "POST_FETCH_ERROR";


export const POST_UPDATE = "POST_UPDATE";
export const POST_UPDATE_START = "POST_UPDATE_START";
export const POST_UPDATE_SUCCESS = "POST_UPDATE_SUCCESS";
export const POST_UPDATE_ERROR = "POST_UPDATE_ERROR";

export const POST_DELETE = "POST_DELETE";
export const POST_DELETE_START = "POST_DELETE_START";
export const POST_DELETE_SUCCESS = "POST_DELETE_SUCCESS";
export const POST_DELETE_ERROR = "POST_DELETE_ERROR";


export const POSTS_CREATE = "POSTS_CREATE";
export const POSTS_CREATE_START = "POSTS_CREATE_START";
export const POSTS_CREATE_SUCCESS = "POSTS_CREATE_SUCCESS";
export const POSTS_CREATE_ERROR = "POSTS_CREATE_ERROR";